Weapon fine tuning
Cubed-Development/Modern-Warfare-Cubed pull request #163
Opened 2023-06-05 19:04 UTC by Koud-Wind

Note: https://github.com/Cubed-Development/Modern-Warfare-Cubed/pull/161 needs to be completed first

2023-06-05 21:49 UTC, Desoroxxx requested changes

2023-06-05 21:49 UTC, Desoroxxx commented on src/main/java/com/paneedah/mwc/items/guns/SupernovaFactory.java
> +        .withInaccuracy(13)
please revert this change (I will do extended research on balance of weapons at a later date)

2023-06-05 21:49 UTC, Desoroxxx commented on src/main/java/com/paneedah/mwc/items/guns/Remington870Factory.java
> +        .withMaxBulletsPerReload(5)
This was correct, so please revert this change.
Refer to https://www.remarms.com/shotguns/pump-action/model-870/

2023-06-05 21:49 UTC, Desoroxxx commented on src/main/java/com/paneedah/mwc/items/guns/Beowulf50CalFactory.java
> +		.withSpawnEntityDamage(10f)
please revert this change (I will do extended research on balance of weapons at a later date)

2023-06-05 21:49 UTC, Desoroxxx commented on src/main/java/com/paneedah/mwc/items/guns/Beowulf50CalFactory.java
> +		"Damage: 10",
please revert this change (I will do extended research on balance of weapons at a later date)

2023-06-05 21:49 UTC, Desoroxxx commented on src/main/java/com/paneedah/mwc/items/guns/AACHoneyBadgerFactory.java
> +                .withSpawnEntityDamage(6.4f)
please revert this change (I will do extended research on balance of weapons at a later date)

2023-06-06 06:40 UTC, Koud-Wind commented
I think authenticity should be a priority because we have a balance pack, and if players feel that balance is not good, they can change the balance themselves. It's better to reduce the head burst damage by a little bit
I don't want VSS to become PUBG like that

2023-06-06 14:39 UTC, Desoroxxx approved these changes

2023-06-06 14:40 UTC, merged