Configurable hipFireSpread
Cubed-Development/Modern-Warfare-Cubed pull request #167
Opened 2023-06-08 18:58 UTC by Koud-Wind

2023-06-09 22:08 UTC, Desoroxxx requested changes

2023-06-09 22:08 UTC, Desoroxxx commented on src/main/java/com/paneedah/weaponlib/WeaponFireAspect.java
> -                   weapon.getSpawnEntityGravityVelocity(), BalancePackManager.getInaccuracy(weapon) + (isAimed ? 0.0f : 2.6f), (float) damage, weapon.getSpawnEntityExplosionRadius(),
Why set the default at 0 wasn't it 2.6 before?

2023-06-10 12:21 UTC, Desoroxxx requested changes

2023-06-10 12:21 UTC, Desoroxxx commented on src/main/java/com/paneedah/weaponlib/WeaponFireAspect.java
> +                   weapon.getSpawnEntityGravityVelocity(), BalancePackManager.getInaccuracy(weapon) + (isAimed ? 0.0f : (float) hipFireSpread), (float) damage, weapon.getSpawnEntityExplosionRadius(),
Why set at 7.5, wasn't it at 2.6 before?

2023-06-13 02:00 UTC, Desoroxxx commented on src/main/java/com/paneedah/weaponlib/WeaponFireAspect.java
> +                   weapon.getSpawnEntityGravityVelocity(), BalancePackManager.getInaccuracy(weapon) + (isAimed ? 0.0f : (float) hipFireSpread), (float) damage, weapon.getSpawnEntityExplosionRadius(),
Any reasons at all?

2023-06-13 07:24 UTC, Koud-Wind commented
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/123817318/2be48e93-9f36-458d-86b3-44a552fa24bb)
![Uploading image.png…]()

2023-06-13 07:27 UTC, Koud-Wind commented
7.5
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/123817318/69ea20a9-0e2e-42ff-91f5-2e9cc1999227)
0.0
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/123817318/4a332328-9994-46b7-bee7-a6619e60c50c)

2023-06-13 15:58 UTC, merged