General adjustments
Cubed-Development/Modern-Warfare-Cubed pull request #189
Opened 2023-07-07 05:16 UTC by Braiam23

## 🤔 What type of PR is this? (check all applicable)

- [ ] 🍕 Addition
- [ ] ⌨️ Productivity
- [X] 🐛 Bug Fix
- [ ] 🔥 Optimization
- [ ] ⚙️ Configuration
- [ ] 🌟 Quality Of Life
- [X] ✨ Enhancement
- [ ] 📝 Documentation

## 📝 Description

fix and renew some more things, maybe in the next one I will fix the accessories of the taurus revolver and the m249 maybe it will fix it

## 🖼️ Screenshots/Recordings
Bug:
![2023-06-22_13 38 04](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/133471454/8f663c19-facd-4f99-a383-144811f5cc7e)

2023-07-07 14:07 UTC, Paneedah commented
Looks good to me. Awaiting review from @Desoroxxx.

2023-07-07 18:35 UTC, Desoroxxx requested changes
Looks good, missing changelog

2023-07-08 16:18 UTC, Braiam23 commented
I already added the changes to the changelog

2023-07-08 17:00 UTC, Desoroxxx approved these changes

2023-07-08 17:00 UTC, merged