Bushmaster ACR with better texture and APC9 Test
Cubed-Development/Modern-Warfare-Cubed pull request #191
Opened 2023-07-08 21:30 UTC by Braiam23

## 🤔 What type of PR is this? (check all applicable)

- [X] 🍕 Addition
- [ ] ⌨️ Productivity
- [ ] 🐛 Bug Fix
- [X] 🔥 Optimization
- [X] ⚙️ Configuration
- [ ] 🌟 Quality Of Life
- [X] ✨ Enhancement
- [ ] 📝 Documentation

## 📝 Description

It is time to give texture to a mythical and old weapon in the mod, on the other hand it is the first test to see how the new weapons work, I doubt that it will break something, I have already tried it many times

## 🖼️ Screenshots/Recordings

![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/133471454/8994269d-795d-43f3-b375-908dcfc3cfc0)
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/133471454/5fa01f7c-1b31-494e-b609-9db971c5e21c)

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [X] 🙅 no documentation needed

2023-07-08 21:31 UTC, Paneedah commented
Could you please provide the Befores?

2023-07-08 21:32 UTC, Braiam23 commented
> Could you please provide the Befores?

I didn't understand how before?

2023-07-08 21:34 UTC, Paneedah commented
Was there no textures before? What exactly did you change?

Or did you update the guns to the new Gun System?

2023-07-08 21:36 UTC, Braiam23 commented
> Was there no textures before? What exactly did you change?
> 
> Or did you update the guns to the new Gun System?

I updated the texture in the acr and in the apc9 the system was updated

2023-07-08 21:36 UTC, Paneedah commented
Could you attach screenshots of what these guns looked like before your changes are applied?

2023-07-08 21:46 UTC, Braiam23 commented
> Could you attach screenshots of what these guns looked like before your changes are applied?

Yes ready

2023-07-08 22:00 UTC, Desoroxxx requested changes
Also missing changelog

2023-07-08 22:01 UTC, Desoroxxx commented
By the way, next pull request it would be a really good idea to delete you entire fork and contact me on Discord to be added to the repository so you can use branches and stay up to date with master it would make everything must cleaner

2023-07-08 22:08 UTC, Braiam23 commented on src/main/java/com/paneedah/mwc/items/guns/APC9Factory.java
> +		.withInaccuracy(2f)
i was testing the Inaccuracy,

2023-07-08 22:08 UTC, Braiam23 commented on src/main/java/com/paneedah/mwc/items/guns/APC9Factory.java
> +        .withShellType(Type.PISTOL)
ok i'll fix it right away

2023-07-08 22:15 UTC, Braiam23 commented
> By the way, next pull request it would be a really good idea to delete you entire fork and contact me on Discord to be added to the repository so you can use branches and stay up to date with master it would make everything must cleaner

sorry that's why I'm using the outdated mod files

2023-07-08 22:18 UTC, Desoroxxx approved these changes

2023-07-08 22:19 UTC, Desoroxxx requested changes
Missing changelog

2023-07-08 22:25 UTC, Braiam23 commented
> Missing changelog

ready

2023-07-09 19:39 UTC, Desoroxxx commented
By the way about the APC, is it working fine are the attachment good how many customization options are there, and also when you are supposed to revamp the weapon for the new system it seems to be essentially the same

2023-07-09 20:48 UTC, Braiam23 commented
> By the way about the APC, is it working fine are the attachment good how many customization options are there, and also when you are supposed to revamp the weapon for the new system it seems to be essentially the same

what are you talking about?

2023-07-09 21:10 UTC, Desoroxxx commented
> > By the way about the APC, is it working fine are the attachment good how many customization options are there, and also when you are supposed to revamp the weapon for the new system it seems to be essentially the same
> 
> what are you talking about? It does work well as a current renewed weapon, with respect to its customization it is related to the model and the APC9 model does not have any accessory that modifies the weapon and regarding whether to pass the weapon from system 1 to system 2 is different in a certain sense because the old code has more modification like the position of the weapon during proning, the recoil and movements of the old animations and that covers many lines

Okay but it would need to be revamped to bring it to the standard of quality, like it needs to have a lot of possible attachements etc...
Look at all the other weapons that use the new system versus the old to see the quality difference

2023-07-09 21:54 UTC, Braiam23 commented
> > > By the way about the APC, is it working fine are the attachment good how many customization options are there, and also when you are supposed to revamp the weapon for the new system it seems to be essentially the same
> > 
> > 
> > what are you talking about? It does work well as a current renewed weapon, with respect to its customization it is related to the model and the APC9 model does not have any accessory that modifies the weapon and regarding whether to pass the weapon from system 1 to system 2 is different in a certain sense because the old code has more modification like the position of the weapon during proning, the recoil and movements of the old animations and that covers many lines
> 
> Okay but it would need to be revamped to bring it to the standard of quality, like it needs to have a lot of possible attachements etc... Look at all the other weapons that use the new system versus the old to see the quality difference

add more content to the weapon?

2023-07-09 22:03 UTC, Desoroxxx commented
> > > > By the way about the APC, is it working fine are the attachment good how many customization options are there, and also when you are supposed to revamp the weapon for the new system it seems to be essentially the same
> > > 
> > > 
> > > what are you talking about? It does work well as a current renewed weapon, with respect to its customization it is related to the model and the APC9 model does not have any accessory that modifies the weapon and regarding whether to pass the weapon from system 1 to system 2 is different in a certain sense because the old code has more modification like the position of the weapon during proning, the recoil and movements of the old animations and that covers many lines
> > 
> > 
> > Okay but it would need to be revamped to bring it to the standard of quality, like it needs to have a lot of possible attachements etc... Look at all the other weapons that use the new system versus the old to see the quality difference
> 
> add more content to the weapon? Or do you mean the texture?

Both

2023-07-09 22:06 UTC, Braiam23 commented
> Both

Honestly, I would like to add more weapon accessories, but there is no time, as far as the texturing is concerned, it is fine because it is similar to the current style of the mod.

2023-07-12 20:05 UTC, Desoroxxx commented
The APC9 seems to be way closer to the camera is that intended

2023-07-13 01:43 UTC, merged