Added custom death messages (#143)
Cubed-Development/Modern-Warfare-Cubed pull request #203
Opened 2023-07-15 20:04 UTC by Paneedah

## 🤔 What type of PR is this? (check all applicable)

- [ ] 🍕 Addition
- [ ] ⌨️ Productivity
- [ ] 🐛 Bug Fix
- [ ] 🔥 Optimization
- [ ] ⚙️ Configuration
- [ ] 🌟 Quality Of Life
- [x] ✨ Enhancement
- [ ] 📝 Documentation

## 📝 Description

Added custom death messages for when someone gets shot!
Current message: "{Player1} was by {Player2} using {WeaponName}"

## 🚦 Testing 

Tested this feature using LAN, since servers are still not working (@Desoroxxx we need that fixed).

## ⏮️ Backwards Compatibility 

Players who do not have the same version as server (or with a lang file that doesn't contain it) will just see `death.attack.gun`.
All languages (apart from `en_US`) will need to update.

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [x] 🙅 no documentation needed

2023-07-15 22:38 UTC, Desoroxxx requested changes
Potential NPE needs to be fixed and changelog entry missing

2023-07-15 22:38 UTC, Desoroxxx commented on src/main/java/com/paneedah/weaponlib/WeaponSpawnEntity.java
> +            position.entityHit.attackEntityFrom(new ProjectileDamageSource("gun", weapon.getName(), this, this.getThrower()), damage);
Removing the null check could cause a null pointer exception in the following cases:
- Player shoot entity, Player disconnects while the bullet is travelling
- Entity shoot player, entity get killed or despawned while the bullet is travelling
etc...

2023-07-16 15:28 UTC, Paneedah commented
@Desoroxxx NPE issue has been resolved.

2023-07-16 15:31 UTC, Desoroxxx approved these changes

2023-07-16 15:31 UTC, merged