Remove VSS Vintorez flash
Cubed-Development/Modern-Warfare-Cubed pull request #308
Opened 2023-11-20 10:55 UTC by MCT32

## 🤔 What type of PR is this? (check all applicable)

- [ ] 🍕 Addition
- [ ] ⌨️ Productivity
- [ ] 🐛 Bug Fix
- [ ] 🔥 Optimization
- [ ] ⚙️ Configuration
- [ ] 🌟 Quality Of Life
- [x] ✨ Enhancement
- [ ] 📝 Documentation

## 📝 Description

Removes the muzzle flash from the VSS Vintorez since according to [wikipedia](https://en.wikipedia.org/wiki/AS_Val_and_VSS_Vintorez#Design), the built in suppressor reduces the flash, and in videos of the gun being used online the flash is not visible.

## 🧐 The Rationale

This change simply make the gun behave more realistically.

## 🎯 Key Objectives

Removing the muzzle flash on the VSS Vintorez

## 🚦 Testing 

Shoot the rifle and observe the flash is gone.

## ⏮️ Backwards Compatibility 

Should be

## 📚 Related Issues & Documents

Fixes #284 

## 🖼️ Screenshots/Recordings

https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/32090502/13e4796b-0fc1-4528-9657-91eb5d74b45e

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [x] 🙅 no documentation needed

## 😄 [optional] What gif best describes this PR or how it makes you feel?

![img](https://media.tenor.com/rGcSfD-4VDcAAAAC/family-guy-peter-griffin.gif)

2023-11-20 12:49 UTC, Desoroxxx commented
Missing changelog entry

2023-11-20 13:04 UTC, Desoroxxx requested changes

2023-11-20 13:04 UTC, Desoroxxx commented on Changelog.md
> +- Removed the muzzle flash from the VSS Vintorez to make it more similar to it's real-life counterpart
Should be in the `Fixed` category and be something along the lines of `Fixed VSS Vintorez having a flash when it shouldn't`

2023-11-20 13:21 UTC, Desoroxxx commented on Changelog.md
> +- Removed the muzzle flash from the VSS Vintorez to make it more similar to it's real-life counterpart
Did you forgot to push, this is still an issue

2023-11-23 18:33 UTC, Braiam23 commented
Thank you very much for the contribution to the mod, but I will move your changes that you made to another Pull request to avoid future conflicts

2023-11-23 18:33 UTC, closed without merging