Previous Commits
Cubed-Development/Modern-Warfare-Cubed pull request #312
Opened 2023-12-01 19:10 UTC by Desoroxxx

## 🤔 What type of PR is this? (check all applicable)

- [ ] 🍕 Addition
- [x] ⌨️ Productivity
- [x] 🐛 Bug Fix
- [x] 🔥 Optimization
- [ ] ⚙️ Configuration
- [ ] 🌟 Quality Of Life
- [ ] ✨ Enhancement
- [ ] 📝 Documentation

## 📝 Description

TBD

## 🧐 The Rationale

TBD

## 🎯 Key Objectives

TBD

## 🚦 Testing 

TBD

## ⏮️ Backwards Compatibility 

This will make weapons in saves disappear, but doesn't matter since we are not even in beta yet.

## 📚 Related Issues & Documents

TBD

## 🖼️ Screenshots/Recordings

TBD

## 📖 Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Javadoc
- [ ] 🍕 Comments
- [x] 🙅 no documentation needed

2023-12-04 19:59 UTC, Braiam23 commented
ready for review

2023-12-18 23:00 UTC, Desoroxxx commented
Fixes #284

2024-01-03 12:15 UTC, Koud-Wind commented
@Desoroxxx Please check these factory files and their aiming positions

2024-02-26 19:16 UTC, Paneedah requested changes
This is my first review. I have to go for now.

2024-02-26 19:16 UTC, Paneedah commented on src/main/java/com/paneedah/mwc/items/guns/M79Factory.java
> +                .withFireRate(0.1f)
No balance changes until 0.2.
```suggestion
                .withFireRate(0.7f)
```

2024-02-26 19:16 UTC, Paneedah commented on src/main/java/com/paneedah/mwc/items/guns/M79Factory.java
> +                .withSpawnEntityDamage(40f)
No balance changes until 0.2.
```suggestion
                .withSpawnEntityDamage(70f)
```

2024-02-26 19:16 UTC, Paneedah commented on src/main/java/com/paneedah/mwc/items/guns/M9A1Factory.java
> +                .withRecoil(5f)
No balance changes until 0.2.
```suggestion
                .withRecoil(2f)
```

2024-02-26 19:16 UTC, Paneedah commented on src/main/java/com/paneedah/mwc/items/guns/M9A1Factory.java
> +                .withInaccuracy(2)
No balance changes until 0.2.
```suggestion
                .withInaccuracy(3)
```

2024-02-26 19:16 UTC, Paneedah commented on src/main/java/com/paneedah/mwc/items/guns/MAC10Factory.java
> +                .withInaccuracy(2f)
No balance changes until 0.2.
```suggestion
                .withInaccuracy(3f)
```

2024-02-26 19:16 UTC, Paneedah commented on src/main/java/com/paneedah/mwc/items/guns/MP40Factory.java
> +                .withFireRate(0.6f)
No balance changes until 0.2.
```suggestion
                .withFireRate(0.55f)
```

2024-02-26 19:16 UTC, Paneedah commented on src/main/java/com/paneedah/mwc/items/guns/MP5A5Factory.java
> +                .withRecoil(1.7f)
No balance changes until 0.2.
```suggestion
                .withRecoil(1.5f)
```

2024-02-27 23:45 UTC, Braiam23 commented on src/main/java/com/paneedah/mwc/items/guns/ACRFactory.java
> +                .withDrawSound("acr_draw")
I will not add something that is unnecessary

2024-02-27 23:46 UTC, Braiam23 commented on src/main/java/com/paneedah/mwc/items/guns/AACHoneyBadgerFactory.java
> +                .withSpawnEntityDamage(6.4f)
👍

2024-02-27 23:47 UTC, Braiam23 commented on src/main/java/com/paneedah/mwc/items/guns/APC9Factory.java
> +                .withInaccuracy(1f)
No

2024-02-28 01:43 UTC, Koud-Wind commented on src/main/java/com/paneedah/mwc/items/guns/ACRFactory.java
> +                .withDrawSound("acr_draw")
> Re-add the removed sounds. Unsure why this was removed in the first place.

Please wait for me to restore it, btw I would like to know the reason

2024-02-28 01:44 UTC, Koud-Wind commented on src/main/java/com/paneedah/mwc/items/guns/APC9Factory.java
> +                .withInaccuracy(1f)
> No balance changes until 0.2 please.

Please wait for me to restore it, btw I would like to know the reason

2024-03-08 23:20 UTC, Paneedah approved these changes

2024-03-08 23:21 UTC, merged